// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PRFactory.Infrastructure.Persistence;

#nullable disable

namespace PRFactory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitPlatform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloneUrl")
                        .IsUnique();

                    b.HasIndex("GitPlatform");

                    b.HasIndex("TenantId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaudeApiKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraApiToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);

                    b.OwnsOne("PRFactory.Domain.Entities.TenantConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ApiTimeoutSeconds")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AutoImplementAfterPlanApproval")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClaudeModel")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("EnableVerboseLogging")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxRetries")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxTokensPerRequest")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Configuration");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", "CustomPromptTemplates", b2 =>
                                {
                                    b2.Property<Guid>("TenantConfigurationTenantId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("Tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.Navigation("CustomPromptTemplates")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementationBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanMarkdownPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("State");

                    b.HasIndex("TenantId");

                    b.HasIndex("TicketKey")
                        .IsUnique();

                    b.HasIndex("State", "TenantId");

                    b.ToTable("Tickets", (string)null);

                    b.OwnsMany("PRFactory.Domain.Entities.Answer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AnsweredAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("QuestionId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId", "Id");

                            b1.ToTable("Tickets");

                            b1.ToJson("Answers");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsMany("PRFactory.Domain.Entities.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId", "Id");

                            b1.ToTable("Tickets");

                            b1.ToJson("Questions");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EventType");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TicketId");

                    b.ToTable("WorkflowEvents", (string)null);

                    b.HasDiscriminator<string>("EventType").HasValue("WorkflowEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Persistence.Entities.WorkflowStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentGraph")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.HasIndex("TicketId", "Status");

                    b.ToTable("WorkflowStates", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.AnswerAdded", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AnswerAdded");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PlanCreated", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PlanCreated");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PullRequestCreated", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PullRequestCreated");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.QuestionAdded", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("QuestionAdded");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowStateChanged", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.Property<string>("From")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("WorkflowStateChanged");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Repositories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Repository", "Repository")
                        .WithMany("Tickets")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tickets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowEvent", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Ticket", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
