// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRFactory.Infrastructure.Persistence;

#nullable disable

namespace PRFactory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109140452_InitialCreateWithTeamReview")]
    partial class InitialCreateWithTeamReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("PRFactory.Domain.Entities.AgentPromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedModel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsSystemTemplate");

                    b.HasIndex("Name");

                    b.HasIndex("TenantId");

                    b.HasIndex("Category", "TenantId");

                    b.HasIndex("Name", "TenantId");

                    b.ToTable("AgentPromptTemplates", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAgentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Checkpoints_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Checkpoints_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Checkpoints_TenantId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_Checkpoints_TicketId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Checkpoints_Status_CreatedAt");

                    b.HasIndex("TicketId", "GraphId")
                        .HasDatabaseName("IX_Checkpoints_TicketId_GraphId");

                    b.HasIndex("TicketId", "GraphId", "Status")
                        .HasDatabaseName("IX_Checkpoints_TicketId_GraphId_Status");

                    b.ToTable("Checkpoints", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.HasIndex("TenantId");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("TenantId", "IsResolved", "Severity");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PlanReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("IX_PlanReviews_ReviewerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PlanReviews_Status");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_PlanReviews_TicketId");

                    b.HasIndex("TicketId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanReviews_TicketId_ReviewerId");

                    b.ToTable("PlanReviews", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitPlatform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloneUrl")
                        .IsUnique();

                    b.HasIndex("GitPlatform");

                    b.HasIndex("TenantId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.ReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MentionedUserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("MentionedUserIds");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_ReviewComments_AuthorId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_ReviewComments_CreatedAt");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_ReviewComments_TicketId");

                    b.ToTable("ReviewComments", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaudeApiKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraApiToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementationBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanMarkdownPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("State");

                    b.HasIndex("TenantId");

                    b.HasIndex("TicketKey")
                        .IsUnique();

                    b.HasIndex("State", "TenantId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.TicketUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TicketId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDescription")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId1");

                    b.HasIndex("IsApproved", "PostedAt")
                        .HasFilter("PostedAt IS NULL");

                    b.HasIndex("TicketId", "IsApproved");

                    b.HasIndex("TicketId", "IsDraft");

                    b.HasIndex("TicketId", "Version");

                    b.ToTable("TicketUpdates", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Users_TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_TenantId_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TicketId");

                    b.ToTable("WorkflowEvents", (string)null);

                    b.HasDiscriminator<string>("EventType").HasValue("WorkflowEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Persistence.Entities.WorkflowStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentGraph")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.HasIndex("TicketId", "Status");

                    b.ToTable("WorkflowStates", (string)null);
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.AnswerAdded", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("AnswerAdded");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PlanCreated", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("PlanCreated");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PullRequestCreated", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("PullRequestCreated");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.QuestionAdded", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("QuestionAdded");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowStateChanged", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("WorkflowStateChanged");
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Events.WorkflowCancelled", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("WorkflowCancelled");
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Events.WorkflowCompleted", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("WorkflowCompleted");
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Events.WorkflowFailed", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("WorkflowFailed");
                });

            modelBuilder.Entity("PRFactory.Infrastructure.Events.WorkflowSuspended", b =>
                {
                    b.HasBaseType("PRFactory.Domain.Entities.WorkflowEvent");

                    b.HasDiscriminator().HasValue("WorkflowSuspended");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.AgentPromptTemplate", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Checkpoint", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.ErrorLog", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.PlanReview", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.User", "Reviewer")
                        .WithMany("PlanReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Ticket", "Ticket")
                        .WithMany("PlanReviews")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Repositories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.ReviewComment", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Ticket", "Ticket")
                        .WithMany("ReviewComments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Tenant", b =>
                {
                    b.OwnsOne("PRFactory.Domain.Entities.TenantConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AllowedRepositories")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ApiTimeoutSeconds")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AutoImplementAfterPlanApproval")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClaudeModel")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("EnableCodeReview")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EnableVerboseLogging")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxRetries")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxTokensPerRequest")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Configuration");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "CustomPromptTemplates", b2 =>
                                {
                                    b2.Property<Guid>("TenantConfigurationTenantId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TenantConfigurationTenantId");

                                    b2.ToTable("Tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantConfigurationTenantId");
                                });

                            b1.Navigation("CustomPromptTemplates")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Repository", "Repository")
                        .WithMany("Tickets")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tickets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, object>", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsMany("PRFactory.Domain.ValueObjects.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id1")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId", "Id1");

                            b1.ToTable("Tickets");

                            b1.ToJson("Questions");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsMany("PRFactory.Domain.ValueObjects.Answer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AnsweredAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("QuestionId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId", "Id");

                            b1.ToTable("Tickets");

                            b1.ToJson("Answers");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Questions");

                    b.Navigation("Repository");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.TicketUpdate", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRFactory.Domain.Entities.Ticket", null)
                        .WithMany("TicketUpdates")
                        .HasForeignKey("TicketId1");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.User", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.WorkflowEvent", b =>
                {
                    b.HasOne("PRFactory.Domain.Entities.Ticket", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.QuestionAdded", b =>
                {
                    b.OwnsOne("PRFactory.Domain.ValueObjects.Question", "Question", b1 =>
                        {
                            b1.Property<Guid>("QuestionAddedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.HasKey("QuestionAddedId");

                            b1.ToTable("WorkflowEvents");

                            b1.ToJson("Question");

                            b1.WithOwner()
                                .HasForeignKey("QuestionAddedId");
                        });

                    b.Navigation("Question")
                        .IsRequired();
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PlanReviews");

                    b.Navigation("ReviewComments");

                    b.Navigation("TicketUpdates");
                });

            modelBuilder.Entity("PRFactory.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PlanReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
