// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRFactory.Infrastructure.Persistence;

#nullable disable

namespace PRFactory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111000000_AddIdentityAndExternalTenantSupport")]
    partial class AddIdentityAndExternalTenantSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            // Model snapshot would be here - will be regenerated by EF Core
            // This is a placeholder to allow the migration to compile
#pragma warning restore 612, 618
        }
    }
}
