namespace PRFactory.Domain.ValueObjects;

/// <summary>
/// Represents a question generated by AI to clarify ticket requirements.
/// </summary>
public class Question
{
    /// <summary>
    /// Unique identifier for the question
    /// </summary>
    public string Id { get; init; } = Guid.NewGuid().ToString();

    /// <summary>
    /// The question text
    /// </summary>
    public required string Text { get; init; }

    /// <summary>
    /// Category of the question (e.g., "requirements", "technical", "testing")
    /// </summary>
    public required string Category { get; init; }

    /// <summary>
    /// When the question was created
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Creates a new question with the specified text and category
    /// </summary>
    public static Question Create(string text, string category)
    {
        if (string.IsNullOrWhiteSpace(text))
            throw new ArgumentException("Question text cannot be empty", nameof(text));

        if (string.IsNullOrWhiteSpace(category))
            throw new ArgumentException("Question category cannot be empty", nameof(category));

        return new Question
        {
            Text = text,
            Category = category,
            CreatedAt = DateTime.UtcNow
        };
    }
}
